// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFREduCRjuakaHkWoYW4ckkOgO_OQfDM',
    appId: '1:920359609590:web:32593145585835f1c2b8d7',
    messagingSenderId: '920359609590',
    projectId: 'chatapp-4fef7',
    authDomain: 'chatapp-4fef7.firebaseapp.com',
    storageBucket: 'chatapp-4fef7.firebasestorage.app',
    measurementId: 'G-HT8DJM9G71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCioYctRTpkhvg9iO45QHX-EwzSNGABpe0',
    appId: '1:920359609590:android:54f07f4fa43ae86cc2b8d7',
    messagingSenderId: '920359609590',
    projectId: 'chatapp-4fef7',
    storageBucket: 'chatapp-4fef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKkMhXBUMsI2Fo4lWwaTVInSv28jydRhs',
    appId: '1:920359609590:ios:66534b1475e01a48c2b8d7',
    messagingSenderId: '920359609590',
    projectId: 'chatapp-4fef7',
    storageBucket: 'chatapp-4fef7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKkMhXBUMsI2Fo4lWwaTVInSv28jydRhs',
    appId: '1:920359609590:ios:66534b1475e01a48c2b8d7',
    messagingSenderId: '920359609590',
    projectId: 'chatapp-4fef7',
    storageBucket: 'chatapp-4fef7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZFREduCRjuakaHkWoYW4ckkOgO_OQfDM',
    appId: '1:920359609590:web:279c40635528c855c2b8d7',
    messagingSenderId: '920359609590',
    projectId: 'chatapp-4fef7',
    authDomain: 'chatapp-4fef7.firebaseapp.com',
    storageBucket: 'chatapp-4fef7.firebasestorage.app',
    measurementId: 'G-CK31GDLCD1',
  );
}
